# Generated by Django 2.1.3 on 2018-12-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=255)),
                ('token', models.CharField(max_length=250, unique=True)),
                ('platform', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=200)),
                ('status', models.BooleanField(choices=[(True, 'online'), (False, 'offline')])),
            ],
        ),
    ]
